[project]
name = "kaggle-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "pydantic==2.6.3",
    "typer>=0.9.0",
    "numba>=0.59.0",
    "hydra-core>=1.3.2",
    "streamlit>=1.32.0",
    "seaborn>=0.13.2",
    "polars>=0.20.15",
    "kaggle>=1.6.6",
    "loguru>=0.7.2",
    "wandb>=0.16.4",
    "tqdm>=4.64.1",
    "lightgbm>=4.3.0",
    "catboost>=1.2.3",
    "transformers>=4.38.2",
    "optuna>=3.5.0",
    "timm>=0.9.16",
    "cudf-cu12>=24.8.0",
    "cuml-cu12>=24.8.0",
]

[tool.uv]
extra-index-url = [
    "https://pypi.nvidia.com",
]
